import esbuild from 'esbuild';
import { writeFileSync } from 'node:fs';
import process from 'process';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE.
Source: https://github.com/K0g1/Templar
*/`;

const production = process.argv[2] === 'production';
const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ['src/main.ts'],
  bundle: true,
  define: {
    Buffer: 'undefined',
    'process.env.LANG': '""',
  },
  external: [
    'obsidian',
    '@codemirror/autocomplete',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr',
  ],
  format: 'cjs',
  logLevel: 'info',
  metafile: production,
  minify: production,
  outfile: 'main.js',
  platform: 'browser',
  sourcemap: production ? false : 'inline',
  target: 'es2021',
  treeShaking: true,
});

if (production) {
  const result = await context.rebuild();
  if (result.metafile) {
    writeFileSync('main.js.meta.json', JSON.stringify(result.metafile));
  }
  await context.dispose();
} else {
  await context.watch();
}
