import esbuild from 'esbuild';
import { writeFileSync } from 'node:fs';
import process from 'process';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE.
Source: https://github.com/K0g1/Templar
*/`;

const mode = process.argv[2] ?? 'development';
const production = mode === 'production';
const profile = mode === 'profile';
const watch = mode === 'development';
const benchmarkSourceCommit = process.env.TEMPLAR_BENCHMARK_SOURCE_COMMIT ??
  'b63adb76ed1843d17b680244370085a0002fc89a';
const instrumentationCommit = process.env.TEMPLAR_INSTRUMENTATION_COMMIT ?? 'working-tree';
const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ['src/main.ts'],
  bundle: true,
  define: {
    Buffer: 'undefined',
    __TEMPLAR_PERF__: profile ? 'true' : 'false',
    __TEMPLAR_PERF_SOURCE_COMMIT__: JSON.stringify(benchmarkSourceCommit),
    __TEMPLAR_PERF_INSTRUMENTATION_COMMIT__: JSON.stringify(instrumentationCommit),
    'process.env.LANG': '""',
  },
  external: [
    'obsidian',
    '@codemirror/autocomplete',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr',
  ],
  format: 'cjs',
  logLevel: 'info',
  metafile: production || profile,
  minify: production,
  outfile: 'main.js',
  platform: 'browser',
  sourcemap: production ? false : 'inline',
  target: 'es2021',
  treeShaking: true,
});

if (production || profile) {
  const result = await context.rebuild();
  if (result.metafile) {
    writeFileSync('main.js.meta.json', JSON.stringify(result.metafile));
  }
  await context.dispose();
} else if (watch) {
  await context.watch();
}
