import type { NotePageOptions, TemplarSettings, TemplarTemplate } from '../types';

export const DEFAULT_PAGE_OPTIONS: NotePageOptions = {
  mode: 'pageless',
  size: 'a4',
  width: 794,
  height: 1123,
  gap: 32,
  scaleToFit: true,
};

const serif = 'Georgia, "Times New Roman", serif';

export const DEFAULT_TEMPLATE: TemplarTemplate = {
  version: 1,
  id: 'untitled-style',
  name: 'Untitled style',
  metadata: {
    author: 'Templar user',
    description: 'A custom Templar style.',
    folder: 'Unfiled',
    tags: [],
  },
  paper: {
    color: '#fffdf7',
    pattern: 'blank',
    patternColor: '#c7d8e5',
    majorPatternColor: '#9fb8ca',
    marginLine: false,
    marginColor: '#df8a8a',
    marginOffset: 72,
    patternOpacity: 1,
    patternScale: 1,
    dotRadius: 1,
    graphMajorInterval: 5,
  },
  baseline: {
    enabled: true,
    mode: 'balanced',
    unit: 30,
    snapImages: true,
  },
  typography: {
    bodyFont: serif,
    bodySize: 18,
    bodyWeight: 400,
    textColor: '#302e2b',
    mutedColor: '#706c66',
    bodyLineHeight: 0,
    firstLineIndent: 0,
    dropCap: false,
  },
  headings: {
    h1: {
      font: serif,
      size: 42,
      weight: 700,
      color: '#302e2b',
      decoration: 'none',
      letterSpacing: 0,
      textTransform: 'none',
    },
    h2: {
      font: serif,
      size: 31,
      weight: 700,
      color: '#393631',
      decoration: 'none',
      letterSpacing: 0,
      textTransform: 'none',
    },
    h3: {
      font: serif,
      size: 24,
      weight: 700,
      color: '#46413b',
      decoration: 'none',
      letterSpacing: 0,
      textTransform: 'none',
    },
    h4: {
      font: serif,
      size: 20,
      weight: 700,
      color: '#514b44',
      decoration: 'none',
      letterSpacing: 0,
      textTransform: 'none',
    },
    h5: {
      font: serif,
      size: 17,
      weight: 700,
      color: '#5a534b',
      decoration: 'none',
      letterSpacing: 0,
      textTransform: 'none',
    },
    h6: {
      font: serif,
      size: 15,
      weight: 700,
      color: '#635c53',
      decoration: 'none',
      letterSpacing: 0,
      textTransform: 'none',
    },
  },
  lists: {
    markerStyle: 'disc',
    markerColor: '#706c66',
    indentGuides: false,
    indentGuideColor: 'rgba(48, 46, 43, 0.18)',
    nestedIndent: 0,
  },
  layout: {
    maxWidth: 820,
    paddingTop: 60,
    paddingRight: 72,
    paddingBottom: 120,
    paddingLeft: 96,
    pageRadius: 0,
    pageShadow: 'none',
  },
  images: {
    frame: 'none',
    borderWidth: 0,
    borderColor: '#ffffff',
    bottomBorderWidth: 0,
    cornerRadius: 0,
    rotation: 0,
    shadow: 'none',
    maxWidth: 100,
    topSpacing: 30,
    bottomSpacing: 30,
    opacity: 1,
    sepia: 0,
    grayscale: 0,
    saturation: 1,
    contrast: 1,
    float: 'none',
    objectFit: 'contain',
    duotone: 'none',
  },
  blocks: {
    linkColor: '#315f86',
    highlightBackground: 'rgba(246, 210, 74, 0.52)',
    highlightTextColor: '#302e2b',
    quoteAccent: '#9fb8ca',
    quoteBackground: 'rgba(159, 184, 202, 0.12)',
    quoteTextColor: '#302e2b',
    codeBackground: 'rgba(48, 46, 43, 0.08)',
    codeTextColor: '#302e2b',
    codeFont: '"SFMono-Regular", Consolas, "Liberation Mono", monospace',
    codeSize: 16,
    tableBorder: 'rgba(48, 46, 43, 0.24)',
    tableHeaderBackground: 'rgba(48, 46, 43, 0.07)',
    tableBorderWidth: 1,
    tableFontSize: 15,
    tableTextColor: '#302e2b',
    tableHeaderTextColor: '#302e2b',
    tablePadding: 8,
    tableStriped: false,
    tableStripeColor: 'rgba(48, 46, 43, 0.045)',
    checkboxAccent: '#507b5c',
    dividerColor: 'rgba(48, 46, 43, 0.35)',
    dividerWidth: 1,
    dividerStyle: 'solid',
    calloutAccent: '#9fb8ca',
    calloutBackground: 'rgba(159, 184, 202, 0.12)',
    calloutTextColor: '#302e2b',
    calloutTitleColor: '#302e2b',
    calloutIconColor: '#9fb8ca',
    calloutBorderWidth: 3,
    calloutRadius: 8,
    calloutVariants: {},
    embedBackground: 'rgba(48, 46, 43, 0.06)',
    embedAccent: '#9fb8ca',
    embedRadius: 10,
  },
  watermark: {
    text: '',
    color: 'rgba(48, 46, 43, 0.1)',
    size: 96,
    rotation: -30,
    opacity: 0.5,
  },
  css: '',
};

export const DEFAULT_SETTINGS: TemplarSettings = {
  enableReadingView: true,
  enableLivePreview: true,
  hideStyleMetadata: true,
  defaultTemplateId: 'classic-ruled',
  defaultGridUnit: 30,
  fontCacheSize: 64,
  favouriteTemplateIds: [],
  recentTemplateIds: [],
  defaultNewPageFlow: 'pageless',
  libraryDensity: 'comfortable',
  styleRules: [],
  userTemplates: [],
};
